version: '3.3'

services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8080
      - AUTHENTICATION_API_KEY=intellimed-secret-key-global
      
      # Banco de Dados
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution@evolution_postgres:5432/evolution
      - DATABASE_URL=postgresql://evolution:evolution@evolution_postgres:5432/evolution
      
      # Cache
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution_redis:6379/0
      
      # Webhook
      - WEBHOOK_GLOBAL_URL=http://host.docker.internal:8000/api/whatsapp/webhook/
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_EVENTS_MESSAGE_UPSERT=true
      
    depends_on:
      evolution_postgres:
        condition: service_healthy
      evolution_redis:
        condition: service_started
    volumes:
      - /dev/null:/evolution/store
    extra_hosts:
      - "host.docker.internal:host-gateway"

  evolution_postgres:
    image: postgres:15-alpine
    container_name: evolution_postgres
    restart: always
    environment:
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=evolution
      - POSTGRES_DB=evolution
    volumes:
      - ./postgres_data_v6:/var/lib/postgresql/data
    healthcheck:
      # Comando de verificação
      test: ["CMD-SHELL", "pg_isready -d evolution -U evolution"]
      interval: 5s
      timeout: 5s
      retries: 15
      # AQUI ESTÁ A CORREÇÃO: Espera até 60s antes de falhar
      start_period: 60s

  evolution_redis:
    image: redis:alpine
    container_name: evolution_redis
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data_v6:/data